name: Build docs for testing doc build

on:
  pull_request:
    branches: ["main"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Upgrade python
        run: python -m pip install --upgrade pip
      - name: Install Packages
        run: python -m pip install -e ".[docs]"
      - name: Build with Sphinx
        run: sphinx-build -M html docs/source/ docs/build/
