name: "Templafirm"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - pyproject.toml
      - requirements/**
      - templafirm/**
      - test/**

# Cancel existing runs when new jobs are spawned from the same branch, excepting master.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  Check_Version:
    name: "Check Version Bump"
    runs-on: ubuntu-24.04 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Templafirm 
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e . 
      - name: Pip Search
        run: |
          export LATEST_VERSION=$(pip search templafirm | sed 's/[^0-9\.\-\/]//g' | sed '$!d')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
      - name: Test Version Bump
        run: |
          CURRENT_VERSION=$(python -c "from importlib.metadata import version;print(version('slack_notifier'))")
          LATEST_VERSION=${{ env.LATEST_VERSION }}
          if [[ "$LATEST_VERSION" == "$CURRENT_VERSION" ]]; then
            echo "Version needs to be bumped in pyproject.toml, version $LATEST_VERSION already exists."
            exit 1
          fi

  Lint_Type_Check_Test_Templafirm:
    name: "Lint, Format, Test, & Type Check Templafirm"
    runs-on: ubuntu-24.04
    needs: [Check_Version]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Upgrade python
        run: python -m pip install --upgrade pip
      - name: Install Packages
        run: python -m pip install -e ".[dev,test]"
      - name: Lint
        run: ruff check templafirm 
      - name: Formatting
        run: ruff format templafirm --check
      - name: Type Check
        run: mypy templafirm 
      - name: Unit Testing
        run: pytest test/unit
